import type { BlogArticle } from "./types";

function article(
  slug: string,
  title: string,
  description: string,
  date: string,
  category: string,
  excerpt: string,
  paragraphs: string[],
): BlogArticle {
  return {
    slug,
    title,
    description,
    date,
    category,
    readTime: "4 min de lecture",
    excerpt,
    body: paragraphs,
  };
}

export const blogArticles: Record<string, BlogArticle> = {
  "reglement-consultation": article(
    "reglement-consultation",
    "Le règlement de consultation (RC) : la pièce qui fixe les règles du jeu",
    "Le RC fixe les règles de déroulement d'un appel d'offres : contenu du dossier, critères de jugement, modalités et date limite de remise.",
    "2026-09-08",
    "Marchés publics",
    "Le règlement de consultation (RC) fixe les règles de déroulement d'un appel d'offres : contenu du dossier, critères de jugement, modalités et date limite de remise. Comment le lire pour ne pas être écarté sur la forme.",
    [
      "Le règlement de consultation est la première pièce à lire dans un DCE. Il fixe les règles du jeu : date et modalités de remise, pièces attendues, critères d'attribution et leur pondération, conditions des variantes.",
      "Une erreur de forme — pièce manquante, format non conforme, dépôt hors délai — élimine l'offre sans même qu'on lise le mémoire technique. Le RC est donc la pièce qui conditionne toute la stratégie de réponse.",
      "Les critères d'attribution y sont détaillés avec leur pondération. C'est cette grille qui doit structurer votre mémoire technique : chaque section doit répondre à un critère noté, dans les proportions attendues par l'acheteur.",
      "Le RC précise aussi si les variantes sont autorisées, si une visite de site est obligatoire, et quelles sont les modalités de dépôt dématérialisé. Chacun de ces points est un piège potentiel à vérifier avant de décider du Go.",
    ],
  ),
  "bordereau-prix-unitaires-bpu": article(
    "bordereau-prix-unitaires-bpu",
    "Le BPU (Bordereau des Prix Unitaires) : rôle, contenu et lien avec le DQE",
    "Le BPU fixe le prix de chaque prestation à l'unité dans un marché à prix unitaires.",
    "2026-09-03",
    "Marchés publics",
    "Le BPU fixe le prix de chaque prestation à l'unité dans un marché à prix unitaires. Ce qu'il contient, pourquoi c'est la pièce qui engage, et comment il s'articule avec le DQE.",
    [
      "Le Bordereau des Prix Unitaires (BPU) liste le prix de chaque prestation à l'unité. Dans les marchés à bons de commande, c'est lui qui s'applique aux quantités réellement commandées pendant l'exécution.",
      "Contrairement au DQE qui est une estimation, le BPU engage contractuellement le candidat sur ses prix unitaires. Une erreur de saisie ou un prix incohérent peut coûter cher sur la durée du marché.",
      "Le DQE (Détail Quantitatif Estimatif) sert à comparer les offres sur des quantités estimées. Il n'engage pas sur les volumes, mais il détermine la note prix à l'attribution.",
      "Lors de la préparation de l'offre, le BPU et le DQE doivent être cohérents : les mêmes postes, les mêmes unités, des prix qui se recoupent. C'est un point de vigilance majeur dans tout DCE financier.",
    ],
  ),
  "seuils-marches-publics": article(
    "seuils-marches-publics",
    "Les seuils des marchés publics : quelle procédure selon le montant",
    "Les seuils déterminent la procédure applicable à un marché public.",
    "2026-09-01",
    "Marchés publics",
    "Les seuils déterminent la procédure applicable à un marché public : gré à gré, procédure adaptée (MAPA) ou procédure formalisée.",
    [
      "Les seuils de marchés publics déterminent la procédure applicable : gré à gré en dessous du seuil de dispense, procédure adaptée (MAPA) entre les seuils, procédure formalisée au-dessus.",
      "Les seuils varient selon la nature du marché (travaux, fournitures, services) et le type d'acheteur (État, collectivité, établissement public). Ils sont révisés régulièrement par la Commission européenne.",
      "Connaître le seuil applicable vous indique le niveau de formalisme à attendre : un MAPA sera plus souple qu'un appel d'offres ouvert, mais reste une vraie mise en concurrence.",
      "Dans votre analyse Go/No-Go, le type de procédure influence la charge de réponse et la probabilité de gain. Un MAPA avec peu de concurrents peut valoir le coup là où un AO ouvert à 15 candidats ne le vaut pas.",
    ],
  ),
  "cctp-cahier-clauses-techniques": article(
    "cctp-cahier-clauses-techniques",
    "Le CCTP : cahier des clauses techniques particulières",
    "Le CCTP décrit le besoin technique et alimente directement le mémoire technique.",
    "2026-08-15",
    "Glossaire",
    "Le CCTP décrit le besoin technique : prestations attendues, exigences de qualité, contraintes d'exécution.",
    [
      "Le Cahier des Clauses Techniques Particulières (CCTP) décrit le besoin technique du marché : prestations attendues, exigences de qualité, contraintes d'exécution, normes applicables.",
      "C'est la matière première du mémoire technique. Chaque exigence du CCTP appelle une réponse dans votre offre : méthodologie, moyens, références, planning.",
      "Le CCTP se lit en parallèle du CCAP (clauses administratives) et du RC (règles de consultation). Les trois pièces forment le cœur décisionnel du DCE.",
      "Une bonne pratique : extraire les exigences du CCTP une par une et les confronter à vos capacités avant de décider du Go. C'est exactement ce que fait la Fiche Synthèse GoNoGo de MateriaBTP.",
    ],
  ),
  "ccap-clauses-administratives": article(
    "ccap-clauses-administratives",
    "Le CCAP : clauses administratives et points de vigilance",
    "Le CCAP fixe les règles administratives propres au marché : pénalités, garanties, paiement.",
    "2026-08-10",
    "Glossaire",
    "Le CCAP fixe les règles administratives propres au marché : pénalités, garanties, conditions de paiement, sous-traitance, résiliation.",
    [
      "Le Cahier des Clauses Administratives Particulières (CCAP) fixe les règles administratives propres au marché : pénalités de retard, garanties, conditions de paiement, sous-traitance, résiliation.",
      "C'est là que se cachent la plupart des risques contractuels. Les dérogations au CCAG sont récapitulées en fin de CCAP et méritent une attention particulière.",
      "Les pénalités de retard, les délais de paiement dérogatoires, les avances sans garantie : autant de points qui doivent être identifiés avant d'engager vos équipes sur la réponse.",
      "MateriaBTP extrait automatiquement ces clauses et les confronte à vos critères de qualification internes dans la Fiche Synthèse GoNoGo.",
    ],
  ),
  "dce-definition-telecharger": article(
    "dce-definition-telecharger",
    "Le DCE : dossier de consultation des entreprises",
    "Le DCE regroupe toutes les pièces remises aux candidats pour répondre à un appel d'offres.",
    "2026-08-05",
    "Glossaire",
    "Le DCE regroupe toutes les pièces remises aux candidats : RC, CCAP, CCTP, acte d'engagement, annexes financières et techniques.",
    [
      "Le Dossier de Consultation des Entreprises (DCE) est l'ensemble des documents remis aux candidats pour répondre : règlement de consultation, CCAP, CCTP, acte d'engagement, annexes financières et techniques.",
      "Sa lecture exhaustive est le prérequis d'un Go/No-Go fiable. Un DCE de marchés publics de travaux peut compter 14 pièces et plusieurs centaines de pages.",
      "Les plateformes de dématérialisation (PLACE, AWS, etc.) permettent de télécharger le DCE complet. MateriaBTP accepte toutes les pièces au format PDF ou Word.",
      "L'analyse automatisée du DCE en quelques minutes remplace des heures de lecture manuelle et réduit le risque d'oublier une clause éliminatoire.",
    ],
  ),
  "dume-guide": article(
    "dume-guide",
    "Le DUME : document unique de marché européen",
    "Le DUME remplace les formulaires DC1/DC2 pour la candidature aux marchés publics.",
    "2026-07-28",
    "Glossaire",
    "Le DUME est une déclaration sur l'honneur standardisée au niveau européen, réutilisable d'une consultation à l'autre.",
    [
      "Le Document Unique de Marché Européen (DUME) est une déclaration sur l'honneur standardisée qui remplace les formulaires DC1/DC2 pour la candidature.",
      "Réutilisable d'une consultation à l'autre, il simplifie le dossier de candidature pour les marchés publics européens.",
      "Le DUME couvre l'identification du candidat, les déclarations sur l'honneur et les capacités. Il peut être complété en ligne sur les plateformes de dématérialisation.",
      "Notre checklist candidature recense les 39 points de contrôle d'un dossier complet, DUME compris.",
    ],
  ),
  "dpgf-decomposition-prix": article(
    "dpgf-decomposition-prix",
    "La DPGF : décomposition du prix global et forfaitaire",
    "La DPGF détaille la construction d'un prix forfaitaire, poste par poste.",
    "2026-07-20",
    "Glossaire",
    "La DPGF détaille la construction d'un prix forfaitaire, poste par poste, pour analyser la cohérence de l'offre financière.",
    [
      "La Décomposition du Prix Global et Forfaitaire (DPGF) est une annexe financière qui détaille la construction d'un prix forfaitaire, poste par poste.",
      "Elle permet à l'acheteur d'analyser la cohérence de l'offre financière et de comparer les postes entre candidats.",
      "Pour le candidat, la DPGF impose de ventiler son prix de manière structurée. Chaque poste doit être justifié et cohérent avec le CCTP.",
      "La DPGF se distingue du BPU (marchés à prix unitaires) et du DQE (quantités estimatives). Bien identifier le type de marché conditionne la préparation financière.",
    ],
  ),
  "dqe-detail-quantitatif": article(
    "dqe-detail-quantitatif",
    "Le DQE : détail quantitatif estimatif",
    "Le DQE sert à comparer les offres de prix dans les marchés à bons de commande.",
    "2026-07-15",
    "Glossaire",
    "Le DQE est une simulation financière établie sur des quantités estimées, souvent utilisée pour comparer les offres de prix.",
    [
      "Le Détail Quantitatif Estimatif (DQE) est une simulation financière établie sur des quantités estimées par l'acheteur.",
      "Il sert à comparer les offres de prix dans les marchés à bons de commande. Non contractuel sur les quantités, il est décisif pour la note prix à l'attribution.",
      "Le DQE reprend les postes du BPU appliqués aux quantités estimées. Cohérence BPU/DQE est un point de contrôle essentiel avant dépôt.",
      "Une offre financière incohérente entre BPU et DQE peut être éliminée ou fortement pénalisée à l'analyse.",
    ],
  ),
  "dc1-lettre-candidature": article(
    "dc1-lettre-candidature",
    "Le DC1 : lettre de candidature",
    "Le DC1 identifie le candidat et porte ses déclarations sur l'honneur.",
    "2026-07-10",
    "Glossaire",
    "Le DC1 identifie le candidat, le groupement et son mandataire, et porte les déclarations sur l'honneur.",
    [
      "Le formulaire DC1 (Lettre de candidature) identifie le candidat ou le groupement et son mandataire.",
      "Il porte les déclarations sur l'honneur : absence d'interdiction de soumissionner, régularité fiscale et sociale.",
      "C'est la première pièce du dossier de candidature, avant le DC2 qui prouve les capacités. Le DUME peut remplacer les deux.",
      "Notre checklist candidature recense les 39 points de contrôle incluant DC1, DC2, DUME et attestations.",
    ],
  ),
  "dc2-declaration-candidat": article(
    "dc2-declaration-candidat",
    "Le DC2 : déclaration du candidat",
    "Le DC2 présente les capacités du candidat : CA, effectifs, références, certifications.",
    "2026-07-05",
    "Glossaire",
    "Le DC2 présente les capacités du candidat : chiffre d'affaires, effectifs, références, moyens techniques et certifications.",
    [
      "Le formulaire DC2 (Déclaration du candidat) présente les capacités : chiffre d'affaires des trois derniers exercices, effectifs, références, moyens techniques et certifications.",
      "Là où le DC1 identifie et engage, le DC2 prouve. Les deux forment le dossier de candidature standard des marchés publics français.",
      "Le DUME européen peut remplacer DC1 et DC2. Vérifiez dans le RC quelle forme est exigée pour chaque consultation.",
      "Centraliser vos références et certifications dans une base de connaissances accélère considérablement le remplissage du DC2.",
    ],
  ),
  "mapa-procedure-adaptee": article(
    "mapa-procedure-adaptee",
    "La MAPA : marché à procédure adaptée",
    "La MAPA est un marché public passé selon des modalités librement définies par l'acheteur.",
    "2026-06-28",
    "Glossaire",
    "La MAPA est un marché public passé selon des modalités librement définies par l'acheteur, en dessous des seuils des procédures formalisées.",
    [
      "Le Marché à Procédure Adaptée (MAPA) est passé selon des modalités librement définies par l'acheteur, en dessous des seuils des procédures formalisées.",
      "Délais plus courts, formalisme allégé, mais une vraie mise en concurrence. Le DCE reste dense et le mémoire technique reste décisif.",
      "MateriaBTP analyse le DCE quelle que soit la procédure. Vos règles de Go/No-Go s'appliquent partout, MAPA comme AO ouvert.",
      "Ne sous-estimez pas un MAPA : moins de candidats ne signifie pas moins de travail, surtout si le montant reste significatif pour votre entreprise.",
    ],
  ),
  "attestation-de-vigilance": article(
    "attestation-de-vigilance",
    "L'attestation de vigilance URSSAF",
    "L'attestation de vigilance prouve qu'une entreprise est à jour de ses cotisations sociales.",
    "2026-06-20",
    "Glossaire",
    "L'attestation de vigilance prouve qu'une entreprise est à jour de ses cotisations sociales. Obligatoire pour tout contrat d'au moins 5 000 €.",
    [
      "L'attestation de vigilance est délivrée par l'URSSAF et prouve qu'une entreprise est à jour de ses cotisations sociales.",
      "L'acheteur l'exige de l'attributaire, et le donneur d'ordre doit la vérifier tous les six mois pour tout contrat d'au moins 5 000 €.",
      "C'est la pièce qui couvre le risque de travail dissimulé. Son absence ou son expiration peut bloquer le paiement des factures.",
      "Notre checklist candidature inclut l'attestation de vigilance parmi les 39 points de contrôle d'un dossier complet.",
    ],
  ),
};

export const blogSlugs = Object.keys(blogArticles);
